micronaut:
  application:
    name: micronautguide
---
#tag::datasource[]
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres  # <1>
    driverClassName: org.postgresql.Driver  # <2>
    dialect: POSTGRES # <2>
    schema-generate: NONE # <3>  
#end::datasource[]
---
#tag::liquibase[]
liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
#end::liquibase[]          