kafka:
  bootstrap:
    servers: # <1>
  security:
    protocol: SASL_SSL
  sasl:
    mechanism: PLAIN
    jaas:
      config:  # <2>
  retries: 3
  max:
    request:
      size: 1048576
    partition:
      fetch:
        bytes: 1048576
