context-path: "/"

micronaut:
    application:
        name: openapi-micronaut
    server:
        port: 8080
    security:
        # authentication: bearer | cookie | session | idtoken

jackson:
    serialization:
        writeEnumsUsingToString: true
        writeDatesAsTimestamps: false
    deserialization:
        readEnumsUsingToString: true
        failOnUnknownProperties: false
        failOnInvalidSubtype: false
