#tag::graphiql[]
graphql:
  graphiql.enabled: true
#end::graphiql[]
---
#tag::datasource[]
datasources:
  default:
    driverClassName: org.postgresql.Driver  # <2>
    dialect: POSTGRES # <3>
    schema-generate: NONE # <4>
    initialization-fail-timeout: 20000
#end::datasource[]
---
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true # <1>
#end::flyway[]
