base-path: "https://api.twitter.com/"
context-path: "/"

# tag::authorization[]
micronaut:
  application:
    name: openapi-micronaut
  server:
    port: 8080
  security:
    oauth2:
      clients:
        twitter: # <1>
          client-id: '${TWITTER_AUTH_CLIENT_ID}' # <4>
          client-secret: '${TWITTER_AUTH_CLIENT_SECRET}'
          client-credentials:
            service-id-regex: '.*' # <5>
          token:
            url: "${base-path}oauth2/token" # <3>
            auth-method: "client_secret_basic" # <2>
# end::authorization[]

jackson:
  serialization:
    writeEnumsUsingToString: true
    writeDatesAsTimestamps: false
  deserialization:
    readEnumsUsingToString: true
    failOnUnknownProperties: false
    failOnInvalidSubtype: false
