#tag::kafka[]
kafka:
  bootstrap:
    servers: # <1>
  security:
    protocol: SASL_SSL
  sasl:
    mechanism: PLAIN
    jaas:
      config:  # <2>
  retries: 3
  max:
    request:
      size: 1048576
    partition:
      fetch:
        bytes: 1048576
#end::kafka[]

#tag::atp[]
datasources:
  default:
    ocid: # <1>
    walletPassword: # <2>
    username: micronautdemo
    password: # <3>

oci:
  config:
    profile: DEFAULT # <4>

flyway:
  datasources:
    default:
      locations:
        - classpath:db/migration/oracle # <5>
#end::atp[]
