#tag::mn[]
micronaut:
  application:
    name: bookcatalogue # <1>
  server:
    port: 8081 # <2>
#end::mn[]
#tag::consul[]
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
#end::consul[]
endpoints:
  health:
    enabled: true
    sensitive: false